### ISSUE TITLE
Aplicar principio OCP

### ISSUE THREAD

**Issue by CesarCarlierESPOL** [angelomedina/Primer-Proyecto-de-POO-Venta-de-Veh-culos-#1]

**Comment by CesarCarlierESPOL** [comment]
Revisando su codico nos encontramos que en la clase Seler ahi un metodo para agregar descuentos al valor de un carro, pero este esta definido en 3 valores fijos. Si se fuera a agregar un valor distinto a este se deberia modificar el código, rompiendo OCP. Se deberia implementar un codigo que reciba un valor variable.

-Este comentario es hecho como parte de un deber para la materia de Diseño de Software, donde se analizan repositorios con la intención de encontrar fallas en la implementacion de los Principios SOLID.

**Comment by angelomedina** [comment]
Hola César Carlier, claro ese proyecto fue sobré PO durante el primer semestre de la carrera y claro tiene muchos errores :), buen día!


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
